# Generated by Django 5.2.2 on 2025-06-16 19:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_user_coins'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('trim_level', models.CharField(blank=True, max_length=50, null=True)),
                ('tier', models.CharField(choices=[('Bronze', 'Bronze'), ('Silver', 'Silver'), ('Gold', 'Gold'), ('Legendary', 'Legendary')], max_length=20)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_hidden', models.BooleanField(default=False)),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('acquired_at', models.DateTimeField(blank=True, null=True)),
                ('acquisition_method', models.CharField(choices=[('purchase', 'Purchase'), ('lottery', 'Lottery')], max_length=20)),
                ('image_url', models.URLField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cars', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
