# Generated by Django 5.2.2 on 2025-06-16 19:59

from django.db import migrations, models
from decimal import Decimal
import datetime

def create_car_data(apps, schema_editor):
    # Get Car model via prev migration
    Car = apps.get_model('main_app', 'Car')
    
    # Create Legendary tier cars (lottery acquisition)
    Car.objects.create(
        make="Bugatti",
        model="Chiron",
        trim_level="Super Sport 300+",
        tier="Legendary",
        cost=Decimal("3200.00"),
        is_hidden=True,
        owner=None,
        purchase_price=None,
        acquired_at=None,
        acquisition_method="lottery",
        image_url="main_app/static/images/cars/bugatti_chiron.jpg",
        created_at=datetime.datetime.now()
    )
    
    Car.objects.create(
        make="McLaren",
        model="Senna",
        trim_level="Coupe",
        tier="Legendary",
        cost=Decimal("3000.00"),
        is_hidden=True,
        owner=None,
        purchase_price=None,
        acquired_at=None,
        acquisition_method="lottery",
        image_url="main_app/static/images/cars/mclaren_senna.jpg",
        created_at=datetime.datetime.now()
    )
    
    Car.objects.create(
        make="Mercedes-Maybach",
        model="G 650",
        trim_level="Landaulet",
        tier="Legendary",
        cost=Decimal("2000.00"),
        is_hidden=True,
        owner=None,
        purchase_price=None,
        acquired_at=None,
        acquisition_method="lottery",
        image_url="main_app/static/images/cars/mercedes_maybach_g650.jpg",
        created_at=datetime.datetime.now()
    )
    
    # Create Gold tier cars
    Car.objects.create(
        make="Porsche",
        model="911",
        trim_level="GT2 RS",
        tier="Gold",
        cost=Decimal("1800.00"),
        is_hidden=False,
        owner=None,
        purchase_price=None,
        acquired_at=None,
        acquisition_method="purchase",
        image_url="main_app/static/images/cars/porsche_gt2_rs.jpg",
        created_at=datetime.datetime.now()
    )
    
    Car.objects.create(
        make="Rezvani",
        model="Vengeance",
        trim_level="Military Executive",
        tier="Gold",
        cost=Decimal("2000.00"),
        is_hidden=False,
        owner=None,
        purchase_price=None,
        acquired_at=None,
        acquisition_method="purchase",
        image_url="main_app/static/images/cars/rezvani_vengeance.jpg",
        created_at=datetime.datetime.now()
    )
    
    Car.objects.create(
        make="Ferrari",
        model="812",
        trim_level="Competizione",
        tier="Gold",
        cost=Decimal("1900.00"),
        is_hidden=False,
        owner=None,
        purchase_price=None,
        acquired_at=None,
        acquisition_method="purchase",
        image_url="main_app/static/images/cars/ferari_812.jpg",
        created_at=datetime.datetime.now()
    )
    
    Car.objects.create(
        make="Lamborghini",
        model="Aventador",
        trim_level="SVJ",
        tier="Gold",
        cost=Decimal("2000.00"),
        is_hidden=False,
        owner=None,
        purchase_price=None,
        acquired_at=None,
        acquisition_method="purchase",
        image_url="main_app/static/images/cars/lamborghini_aventador.jpg",
        created_at=datetime.datetime.now()
    )
    
    # Create Silver tier cars
    Car.objects.create(
        make="BMW",
        model="M4",
        trim_level="Competition",
        tier="Silver",
        cost=Decimal("1100.00"),
        is_hidden=False,
        owner=None,
        purchase_price=None,
        acquired_at=None,
        acquisition_method="purchase",
        image_url="main_app/static/images/cars/bmw_m4.jpg",
        created_at=datetime.datetime.now()
    )
    
    Car.objects.create(
        make="Ford",
        model="F-150",
        trim_level="Raptor R",
        tier="Silver",
        cost=Decimal("1200.00"),
        is_hidden=False,
        owner=None,
        purchase_price=None,
        acquired_at=None,
        acquisition_method="purchase",
        image_url="main_app/static/images/cars/ford_f150.jpg",
        created_at=datetime.datetime.now()
    )
    
    Car.objects.create(
        make="Porsche",
        model="Cayman",
        trim_level="S",
        tier="Silver",
        cost=Decimal("1000.00"),
        is_hidden=False,
        owner=None,
        purchase_price=None,
        acquired_at=None,
        acquisition_method="purchase",
        image_url="main_app/static/images/cars/porsche_cayman.jpg",
        created_at=datetime.datetime.now()
    )
    
    Car.objects.create(
        make="Mercedes-AMG",
        model="C 63",
        trim_level="S",
        tier="Silver",
        cost=Decimal("1200.00"),
        is_hidden=False,
        owner=None,
        purchase_price=None,
        acquired_at=None,
        acquisition_method="purchase",
        image_url="main_app/static/images/cars/mercedes_amg_c63.jpg",
        created_at=datetime.datetime.now()
    )
    
    # Create Bronze tier cars
    Car.objects.create(
        make="Ford",
        model="Mustang",
        trim_level="Dark Horse",
        tier="Bronze",
        cost=Decimal("600.00"),
        is_hidden=False,
        owner=None,
        purchase_price=None,
        acquired_at=None,
        acquisition_method="purchase",
        image_url="main_app/static/images/cars/ford_mustang.jpg",
        created_at=datetime.datetime.now()
    )
    
    Car.objects.create(
        make="Toyota",
        model="GR Supra",
        trim_level="3.0",
        tier="Bronze",
        cost=Decimal("400.00"),
        is_hidden=False,
        owner=None,
        purchase_price=None,
        acquired_at=None,
        acquisition_method="purchase",
        image_url="main_app/static/images/cars/toyota_supra.jpg",
        created_at=datetime.datetime.now()
    )
    
    Car.objects.create(
        make="Jeep",
        model="Wrangler",
        trim_level="Rubicon",
        tier="Bronze",
        cost=Decimal("600.00"),
        is_hidden=False,
        owner=None,
        purchase_price=None,
        acquired_at=None,
        acquisition_method="purchase",
        image_url="main_app/static/images/cars/jeep_wrangler.jpg",
        created_at=datetime.datetime.now()
    )
    
    Car.objects.create(
        make="Lexus",
        model="RC F",
        trim_level=None,
        tier="Bronze",
        cost=Decimal("500.00"),
        is_hidden=False,
        owner=None,
        purchase_price=None,
        acquired_at=None,
        acquisition_method="purchase",
        image_url="main_app/static/images/cars/lexus_rcf.jpg",
        created_at=datetime.datetime.now()
    )

class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_car_created_at'),
    ]

    operations = [
        migrations.RunPython(create_car_data),
    ]
